1. How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
import pandas as pd

outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000
n_dice = 2


die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

(die1 == die2).mean()

0.1687

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [2]:
results = np.random.choice((0,1), size=(1_000_000, 8))
(results.sum(axis=1) == 3).mean()

0.2181

In [3]:
(results.sum(axis=1) > 3).mean()

0.637077

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [4]:
billboards = np.random.choice((0,1), size = (1_000_000, 2), p=(.75, .25))
(billboards.sum(axis=1) == 2).mean()
# In this scenario 0 is web dev and 1 is data science. Because the ratio is 3 to 1, I've added the p variable giving each the appropriate weight. 


0.062326

In [5]:
1/16

0.0625

4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [6]:
s = np.random.normal(3, 1.5, size=(1000, 5))
(s.sum(axis=1) < 17).mean()

0.755

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [7]:
men = np.random.normal(178, 8, size=(1000))
women = np.random.normal(170, 6, size=(1000))

df = pd.DataFrame()
df['men'] = men
df['women'] = women

df



men       women
0    180.196121  170.273367
1    181.901180  182.357205
2    156.708740  162.340342
3    185.706764  171.040041
4    170.204443  168.014717
..          ...         ...
995  178.889325  168.104911
996  176.635747  162.442415
997  172.504299  172.202889
998  173.117184  164.132550
999  182.249513  155.758414

[1000 rows x 2 columns]

In [8]:
(df.women > df.men).mean()

0.194

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [9]:
s = np.random.choice((0, 1), size=50, p=(249/250, 1/250))
s

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [10]:
1 - s.mean()
#Chances of 50 students downloading anaconda successfully

1.0

In [11]:
s = np.random.choice((0, 1), size=100, p=(249/250, 1/250))
1 - s.mean()
#Chances of 100 students downloading anaconda successfully

1.0

In [12]:
s = np.random.choice((0, 1), size=150, p=(249/250, 1/250))
s.mean()
#Chances of someone out of 150 students downloading anaconda unsuccessfully

0.006666666666666667

In [13]:
s = np.random.choice((0, 1), size=450, p=(249/250, 1/250))
1 - s.mean()
#Chances of 450 students downloading anaconda successfully

0.9933333333333333

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?

In [14]:
ft = .7
days = 3
n_rows = 10000

data = np.random.random((n_rows, days))
data

array([[0.15179351, 0.48343661, 0.04615948],
       [0.08251811, 0.92748037, 0.32169666],
       [0.80793174, 0.72498773, 0.65120774],
       ...,
       [0.44181032, 0.47972329, 0.09701093],
       [0.20591351, 0.9877841 , 0.92891054],
       [0.15339633, 0.78840905, 0.13026208]])

In [15]:
present = data < ft
present

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True],
       ...,
       [ True,  True,  True],
       [ True, False, False],
       [ True, False,  True]])

In [16]:
(present.sum(axis=1) == 0).mean()

0.0249

In [17]:
(present.sum(axis=1) > 0).mean()

0.9751

In [18]:
.3*.3*.3

0.027

In [19]:
.3**7

0.00021869999999999995

In [20]:
data = np.random.random((n_rows, 7))
present = data < ft
(present.sum(axis=1) > 0).mean()

1.0

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [42]:
data = np.random.uniform(1, 365, size=(10000, 23))
df = pd.DataFrame(data)
sample = df.round(0)
sample


0      1      2      3      4      5      6      7      8      9   \
0      26.0  356.0   94.0  279.0  330.0  362.0  300.0  307.0  253.0  130.0   
1     316.0  312.0  233.0  183.0  177.0   37.0  140.0  294.0  102.0  227.0   
2     340.0  183.0   26.0  178.0  174.0  288.0   54.0  332.0  138.0  332.0   
3     327.0  190.0   70.0  246.0  176.0  115.0  279.0  175.0  353.0   70.0   
4     226.0  102.0  174.0   96.0  156.0   90.0   28.0   78.0  165.0  232.0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9995  343.0  201.0   74.0  316.0  258.0  332.0  234.0  215.0  244.0  356.0   
9996  129.0  194.0  330.0  147.0  174.0   89.0  234.0  106.0   94.0  141.0   
9997  361.0  240.0  154.0  268.0  243.0  346.0  245.0   45.0  100.0    7.0   
9998  230.0  157.0   27.0  191.0  247.0   95.0  179.0  266.0  245.0  319.0   
9999  343.0   60.0  193.0  210.0  348.0  164.0   60.0  312.0   98.0  175.0   

      ...     13     14     15     16     17     18     19     20     21  \
0     ...  281.0  328.0  262.0  300.0  126.0  301.0  323.0  192.0  185.0   
1     ...  188.0  346.0  129.0   10.0   12.0   24.0  165.0  106.0  348.0   
2     ...   96.0  234.0  224.0  256.0  202.0  204.0  227.0  280.0   58.0   
3     ...  149.0  151.0   17.0  173.0  271.0  347.0  303.0   62.0  249.0   
4     ...  160.0  149.0  329.0  339.0  158.0  130.0  246.0  355.0  278.0   
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9995  ...  193.0  105.0  119.0  200.0  169.0  353.0   83.0  287.0  174.0   
9996  ...   40.0  169.0  340.0  284.0   50.0   95.0  178.0  115.0   95.0   
9997  ...  308.0  331.0  238.0  134.0   53.0  214.0  155.0   20.0  258.0   
9998  ...  306.0  295.0  217.0  106.0  178.0  107.0  174.0   43.0  151.0   
9999  ...  118.0  164.0  251.0  182.0  128.0  309.0  155.0    7.0  174.0   

         22  
0     328.0  
1      72.0  
2     172.0  
3     278.0  
4     255.0  
...     ...  
9995  176.0  
9996  122.0  
9997  124.0  
9998  263.0  
9999  349.0  

[10000 rows x 23 columns]

In [43]:
no_one = sample.apply(lambda row: row.is_unique, axis=1)
no_one

0       False
1        True
2       False
3       False
4        True
        ...  
9995     True
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

In [44]:
1-no_one.mean()

0.5032

Question 8 example given

In [ ]:
nrows = 100000
ncols = 23
birthdays = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)